<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRp1bjWA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRp1bjWA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRp1bjWA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRp1bjWA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRp1bjWA\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rp1bjWA',
    'container.build_id' => 'e86acb89',
    'container.build_time' => 1754167830,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRp1bjWA');
