security:
  # Configuration du hachage des mots de passe
  password_hashers:
    App\Entity\User:
      algorithm: auto # Choix automatique du meilleur algo selon l’environnement

  # Fournisseur d’utilisateurs basé sur l’entité User (identification par email)
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # Définition des firewalls (zones de sécurité)
  firewalls:
    # Zone de développement (profiler, assets) — pas de sécurité
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # Zone principale sécurisée
    main:
      lazy: true # Authentification paresseuse (optimisation perf)
      provider: app_user_provider

      # Authentificateur personnalisé (LoginAuthenticator)
      custom_authenticators:
        - App\Security\LoginAuthenticator

      # Configuration de la déconnexion
      logout:
        path: /auth/logout
        target: /auth/logged-out
        invalidate_session: true

      # Fonction "Se souvenir de moi"
      remember_me:
        secret: '%kernel.secret%' # Clé secrète pour le cookie
        lifetime: 604800 # Durée en secondes (7 jours)
        path: /
        name: REMEMBERME
        always_remember_me: false

  # Contrôle d’accès par URL et rôle
  access_control:
    # Accès public aux pages d’authentification
    - { path: ^/auth/login, roles: PUBLIC_ACCESS }
    - { path: ^/auth/register, roles: PUBLIC_ACCESS }
    - { path: ^/auth/logout, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/auth/logged-out, roles: PUBLIC_ACCESS }

    # Accès réservé aux utilisateurs connectés
    - { path: ^/account/upload-avatar, roles: ROLE_USER }
    # Accès réservé aux admins connectés
    - { path: ^/dashboard, roles: ROLE_ADMIN }

    # Routes réservées aux admins ou super admins :
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/super-admin, roles: ROLE_SUPER_ADMIN }

  # Hiérarchie des rôles (héritage automatique)
  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER] # Un admin hérite des droits d’un user
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH] # Super admin = admin + switch d’utilisateur

# Configuration spécifique pour les tests
when@test:
  security:
    password_hashers:
      App\Entity\User:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10