services:
  php:
    build:
      context: ./docker/php
    container_name: symfony_php
    volumes:
      - ./morningsoul:/var/www/html
    environment:
      MAILER_DSN: smtp://9891719dad3ab0cdae835bbef994a418:ee42e2b13014092121a2385a51832f6b@smtp.mailjet.com:587
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./morningsoul:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/nginx/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/nginx/certs/privkey.pem:/etc/nginx/certs/privkey.pem
    depends_on:
      - php

  db:
    image: mysql:8.0.42
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
