version: '3.8'

services:
  php:
    build: 
      context: ./docker/php
    container_name: symfony_php
    volumes:
      - ./Symfony_project:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    environment:
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_app
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./symfony_project:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  mysql_data: