<?php

namespace ContainerFKvurwj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U8YN5gSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.U8YN5gS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.U8YN5gS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AccountController::profile' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\AccountController::profile()', 'getAccountControllerprofileService', true],
            'App\\Controller\\AuthController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\AuthController::login()', 'getAuthControllerloginService', true],
            'App\\Controller\\AuthController::register' => ['privates', '.service_locator.3PbG7Du.App\\Controller\\AuthController::register()', 'getAuthControllerregisterService', true],
            'App\\Controller\\AuthDebugController::debug' => ['privates', '.service_locator.lQAlGdR.App\\Controller\\AuthDebugController::debug()', 'getAuthDebugControllerdebugService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AccountController:profile' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\AccountController::profile()', 'getAccountControllerprofileService', true],
            'App\\Controller\\AuthController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\AuthController::login()', 'getAuthControllerloginService', true],
            'App\\Controller\\AuthController:register' => ['privates', '.service_locator.3PbG7Du.App\\Controller\\AuthController::register()', 'getAuthControllerregisterService', true],
            'App\\Controller\\AuthDebugController:debug' => ['privates', '.service_locator.lQAlGdR.App\\Controller\\AuthDebugController::debug()', 'getAuthDebugControllerdebugService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AccountController::profile' => '?',
            'App\\Controller\\AuthController::login' => '?',
            'App\\Controller\\AuthController::register' => '?',
            'App\\Controller\\AuthDebugController::debug' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AccountController:profile' => '?',
            'App\\Controller\\AuthController:login' => '?',
            'App\\Controller\\AuthController:register' => '?',
            'App\\Controller\\AuthDebugController:debug' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
